#!/bin/sh

## Get password name
password_name=$(ls $PASSWORD_STORE_DIR | sed 's/\.gpg$//' | fzf --pointer '=>' --layout reverse --info hidden --header 'Select a Password')

# Exit if no password is selected
[ -z "$password_name" ] && exit

# Copy password
pass -c "$password_name"
