#!/bin/bash

read -p "Enter name of password: " passName
read -p "Enter length of password: " passLength
[[ ! "$passLength" =~ ^[0-9]+$ ]] &&
  echo "Error: invalid input. expected a number(positive)" &&
  read -p "Press enter to exit." && exit 1
pass generate -c $passName $passLength
