input {
    kb_layout = us,pk
    kb_options = grp:alt_altgr_toggle,caps:swapescape
    sensitivity = 0.8

    touchpad {
        natural_scroll = true
        disable_while_typing = $touchpadDisableTyping
        scroll_factor = $touchpadScrollFactor
    }
}

gestures {
    gesture = 3, horizontal, workspace
}
